name: LobbyWands
main: com.sandlotminecraft.lobbywands.LobbyWands
version: 1.0
commands:
    wands:
        description: null
        usage: /<command>
        permission: group.moderator
        permission-message: You don't have permission